package domain;

public enum Currency {
    AED("Dirham dos Emirados Árabes Unidos","United Arab Emirates"),
    AFN("Afegane Afegão","Afghanistan"),
    ALL("Lek Albanês","Albania"),
    AMD("Dram Armênio","Armenia"),
    ANG("Florim das Antilhas Neerlandesas","Netherlands Antilles"),
    AOA("Kwanza Angolano","Angola"),
    ARS("Peso Argentino","Argentina"),
    AUD("Dólar Australiano","Australia"),
    AWG("Florim Arubano","Aruba"),
    AZN("Manat Azerbaijano","Azerbaijan"),
    BAM("Marco da Bósnia-Herzegovina","Bosnia and Herzegovina"),
    BBD("Dólar de Barbados","Barbados"),
    BDT("Taka de Bangladesh","Bangladesh"),
    BGN("Lev Búlgaro","Bulgaria"),
    BHD("Dinar do Bahrein","Bahrain"),
    BIF("Franco Burundiano","Burundi"),
    BMD("Dólar Bermudense","Bermuda"),
    BND("Dólar de Brunei","Brunei"),
    BOB("Boliviano","Bolivia"),
    BRL("Real Brasileiro","Brazil"),
    BSD("Dólar das Bahamas","Bahamas"),
    BTN("Ngultrum Butanês","Bhutan"),
    BWP("Pula de Botswana","Botswana"),
    BYN("Rublo Bielorrusso","Belarus"),
    BZD("Dólar de Belize","Belize"),
    CAD("Dólar Canadense","Canada"),
    CDF("Franco Congolês","Democratic Republic of the Congo"),
    CHF("Franco Suíço","Switzerland"),
    CLP("Peso Chileno","Chile"),
    CNY("Renminbi Chinês","China"),
    COP("Peso Colombiano","Colombia"),
    CRC("Colón Costarriquenho","Costa Rica"),
    CUP("Peso Cubano","Cuba"),
    CVE("Escudo Cabo-Verdiano","Cape Verde"),
    CZK("Coroa Tcheca","Czech Republic"),
    DJF("Franco do Djibouti","Djibouti"),
    DKK("Coroa Dinamarquesa","Denmark"),
    DOP("Peso Dominicano","Dominican Republic"),
    DZD("Dinar Argelino","Algeria"),
    EGP("Libra Egípcia","Egypt"),
    ERN("Nakfa Eritreia","Eritrea"),
    ETB("Birr Etíope","Ethiopia"),
    EUR("Euro","European Union"),
    FJD("Dólar de Fiji","Fiji"),
    FKP("Libra das Ilhas Malvinas","Falkland Islands"),
    FOK("Coroa Faroesa","Faroe Islands"),
    GBP("Libra Esterlina","United Kingdom"),
    GEL("Lari Georgiano","Georgia"),
    GGP("Libra de Guernsey","Guernsey"),
    GHS("Cedi Ganês","Ghana"),
    GIP("Libra de Gibraltar","Gibraltar"),
    GMD("Dalasi Gambiano","The Gambia"),
    GNF("Franco Guineano","Guinea"),
    GTQ("Quetzal Guatemalteco","Guatemala"),
    GYD("Dólar Guianense","Guyana"),
    HKD("Dólar de Hong Kong","Hong Kong"),
    HNL("Lempira Hondurenha","Honduras"),
    HRK("Kuna Croata","Croatia"),
    HTG("Gourde Haitiano","Haiti"),
    HUF("Forint Húngaro","Hungary"),
    IDR("Rupia Indonésia","Indonesia"),
    ILS("Novo Shekel Israelense","Israel"),
    IMP("Libra de Man","Isle of Man"),
    INR("Rupia Indiana","India"),
    IQD("Dinar Iraquiano","Iraq"),
    IRR("Rial Iraniano","Iran"),
    ISK("Coroa Islandesa","Iceland"),
    JEP("Libra de Jersey","Jersey"),
    JMD("Dólar Jamaicano","Jamaica"),
    JOD("Dinar Jordaniano","Jordan"),
    JPY("Iene Japonês","Japan"),
    KES("Xelim Queniano","Kenya"),
    KGS("Som Quirguiz","Kyrgyzstan"),
    KHR("Riel Cambojano","Cambodia"),
    KID("Dólar de Kiribati","Kiribati"),
    KMF("Franco Comorense","Comoros"),
    KRW("Won Sul-Coreano","South Korea"),
    KWD("Dinar Kuwaitiano","Kuwait"),
    KYD("Dólar das Ilhas Cayman","Cayman Islands"),
    KZT("Tenge Cazaque","Kazakhstan"),
    LAK("Kip Laociano","Laos"),
    LBP("Libra Libanesa","Lebanon"),
    LKR("Rupia do Sri Lanka","Sri Lanka"),
    LRD("Dólar Liberiano","Liberia"),
    LSL("Loti do Lesoto","Lesotho"),
    LYD("Dinar Líbio","Libya"),
    MAD("Dirham Marroquino","Morocco"),
    MDL("Leu Moldavo","Moldova"),
    MGA("Ariary Malgaxe","Madagascar"),
    MKD("Dinar Macedônio","North Macedonia"),
    MMK("Kyat Birmanês","Myanmar"),
    MNT("Tugrik Mongol","Mongolia"),
    MOP("Pataca de Macau","Macau"),
    MRU("Ouguiya Mauritana","Mauritania"),
    MUR("Rupia Mauriciana","Mauritius"),
    MVR("Rufiyaa Maldiva","Maldives"),
    MWK("Kwacha Malauiano","Malawi"),
    MXN("Peso Mexicano","Mexico"),
    MYR("Ringgit Malaio","Malaysia"),
    MZN("Metical Moçambicano","Mozambique"),
    NAD("Dólar Namibiano","Namibia"),
    NGN("Naira Nigeriana","Nigeria"),
    NIO("Córdoba Nicaraguense","Nicaragua"),
    NOK("Coroa Norueguesa","Norway"),
    NPR("Rupia Nepalesa","Nepal"),
    NZD("Dólar Neozelandês","New Zealand"),
    OMR("Rial Omanense","Oman"),
    PAB("Balboa Panamenho","Panama"),
    PEN("Sol Peruano","Peru"),
    PGK("Kina Papua-Nova-Guinense","Papua New Guinea"),
    PHP("Peso Filipino","Philippines"),
    PKR("Rupia Paquistanesa","Pakistan"),
    PLN("Złoty Polonês","Poland"),
    PYG("Guarani Paraguaio","Paraguay"),
    QAR("Rial Catariano","Qatar"),
    RON("Leu Romeno","Romania"),
    RSD("Dinar Sérvio","Serbia"),
    RUB("Rublo Russo","Russia"),
    RWF("Franco Ruandês","Rwanda"),
    SAR("Rial Saudita","Saudi Arabia"),
    SBD("Dólar das Ilhas Salomão","Solomon Islands"),
    SCR("Rupia de Seychelles","Seychelles"),
    SDG("Libra Sudanesa","Sudan"),
    SEK("Coroa Sueca","Sweden"),
    SGD("Dólar de Singapura","Singapore"),
    SHP("Libra de Santa Helena","Saint Helena"),
    SLE("Leone de Serra Leoa","Sierra Leone"),
    SOS("Xelim Somali","Somalia"),
    SRD("Dólar do Suriname","Suriname"),
    SSP("Libra do Sudão do Sul","South Sudan"),
    STN("Dobra de São Tomé e Príncipe","São Tomé and Príncipe"),
    SYP("Libra Síria","Syria"),
    SZL("Lilangeni de Essuatíni","Eswatini"),
    THB("Baht Tailandês","Thailand"),
    TJS("Somoni Tadjique","Tajikistan"),
    TMT("Manat do Turcomenistão","Turkmenistan"),
    TND("Dinar Tunisiano","Tunisia"),
    TOP("Paʻanga de Tonga","Tonga"),
    TRY("Lira Turca","Turkey"),
    TTD("Dólar de Trinidad e Tobago","Trinidad and Tobago"),
    TVD("Dólar de Tuvalu","Tuvalu"),
    TWD("Novo Dólar Taiwanês","Taiwan"),
    TZS("Xelim Tanzaniano","Tanzania"),
    UAH("Hryvnia Ucraniana","Ukraine"),
    UGX("Xelim Ugandês","Uganda"),
    USD("Dólar dos Estados Unidos","United States"),
    UYU("Peso Uruguaio","Uruguay"),
    UZS("Som Uzbeque","Uzbekistan"),
    VES("Bolívar Venezuelano","Venezuela"),
    VND("Dong Vietnamita","Vietnam"),
    VUV("Vatu de Vanuatu","Vanuatu"),
    WST("Tālā Samoano","Samoa"),
    XAF("Franco CFA Central","CEMAC"),
    XCD("Dólar do Caribe Oriental","Organisation of Eastern Caribbean States"),
    XDR("Direitos Especiais de Saque","International Monetary Fund"),
    XOF("Franco CFA Ocidental","CFA"),
    XPF("Franco CFP","Collectivités d' Outre-Mer"),
    YER("Rial Iemenita","Yemen"),
    ZAR("Rand Sul-Africano","South Africa"),
    ZMW("Kwacha Zambiano","Zambia"),
    ZWL("Dólar do Zimbábue","Zimbabwe");

    final String name;
    final String country;

    Currency(String s, String s1) {
        this.name = s;
        this.country = s1;
    }

    public static Currency fromName(String name){
        for(Currency c : Currency.values()){
            if(c.name.equalsIgnoreCase(name)){
                return c;
            }
        }
        throw new IllegalArgumentException("Não foi encontrado nenhum registro da moeda " + name);
    }

    public String getName() {
        return name;
    }

    public String getCountry() {
        return country;
    }
}
